// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: carrotmember/member.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Member struct {
	Creator       string     `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	MemberAddress string     `protobuf:"bytes,2,opt,name=member_address,json=memberAddress,proto3" json:"member_address,omitempty"`
	TotalCnt      uint64     `protobuf:"varint,3,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	RemainCnt     uint64     `protobuf:"varint,4,opt,name=remain_cnt,json=remainCnt,proto3" json:"remain_cnt,omitempty"`
	Amount        types.Coin `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount"`
	CreateTime    time.Time  `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3,stdtime" json:"create_time"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a3a7234c169584a, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Member.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return m.Size()
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Member) GetMemberAddress() string {
	if m != nil {
		return m.MemberAddress
	}
	return ""
}

func (m *Member) GetTotalCnt() uint64 {
	if m != nil {
		return m.TotalCnt
	}
	return 0
}

func (m *Member) GetRemainCnt() uint64 {
	if m != nil {
		return m.RemainCnt
	}
	return 0
}

func (m *Member) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *Member) GetCreateTime() time.Time {
	if m != nil {
		return m.CreateTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Member)(nil), "hupayxcom.carrotmember.carrotmember.Member")
}

func init() { proto.RegisterFile("carrotmember/member.proto", fileDescriptor_0a3a7234c169584a) }

var fileDescriptor_0a3a7234c169584a = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x3f, 0x4f, 0xfa, 0x40,
	0x18, 0xee, 0xf1, 0xe3, 0x57, 0xe1, 0x88, 0x0e, 0x8d, 0x43, 0xc1, 0x58, 0x88, 0xc6, 0x84, 0xc5,
	0xbb, 0xa0, 0x03, 0xb3, 0x10, 0x47, 0x07, 0x1b, 0x27, 0x17, 0x72, 0x2d, 0x67, 0x69, 0xc2, 0xf5,
	0x6d, 0xee, 0xae, 0x06, 0x3e, 0x80, 0x3b, 0x1f, 0x8b, 0x91, 0xd1, 0x49, 0x0d, 0x7c, 0x11, 0x73,
	0x77, 0x90, 0xc8, 0xd4, 0x7b, 0x9f, 0x3f, 0x79, 0x9f, 0x3e, 0x2f, 0x6e, 0xa7, 0x4c, 0x4a, 0xd0,
	0x82, 0x8b, 0x84, 0x4b, 0xea, 0x3e, 0xa4, 0x94, 0xa0, 0x21, 0xb8, 0x9e, 0x55, 0x25, 0x5b, 0x2e,
	0x52, 0x10, 0xe4, 0xaf, 0xe8, 0x68, 0xe8, 0x9c, 0x67, 0x90, 0x81, 0xd5, 0x53, 0xf3, 0x72, 0xd6,
	0x4e, 0x37, 0x03, 0xc8, 0xe6, 0x9c, 0xda, 0x29, 0xa9, 0xde, 0xa8, 0xce, 0x05, 0x57, 0x9a, 0x89,
	0x72, 0x2f, 0x88, 0x52, 0x50, 0x02, 0x14, 0x4d, 0x98, 0xe2, 0xf4, 0x7d, 0x90, 0x70, 0xcd, 0x06,
	0x34, 0x85, 0xbc, 0x70, 0xfc, 0xd5, 0x47, 0x0d, 0xfb, 0x4f, 0x76, 0x43, 0x10, 0xe2, 0x93, 0x54,
	0x72, 0xa6, 0x41, 0x86, 0xa8, 0x87, 0xfa, 0xcd, 0xf8, 0x30, 0x06, 0x37, 0xf8, 0xcc, 0xa5, 0x98,
	0xb0, 0xe9, 0x54, 0x72, 0xa5, 0xc2, 0x9a, 0x15, 0x9c, 0x3a, 0xf4, 0xc1, 0x81, 0xc1, 0x05, 0x6e,
	0x6a, 0xd0, 0x6c, 0x3e, 0x49, 0x0b, 0x1d, 0xfe, 0xeb, 0xa1, 0x7e, 0x3d, 0x6e, 0x58, 0x60, 0x5c,
	0xe8, 0xe0, 0x12, 0x63, 0xc9, 0x05, 0xcb, 0x0b, 0xcb, 0xd6, 0x2d, 0xdb, 0x74, 0x88, 0xa1, 0x87,
	0xd8, 0x67, 0x02, 0xaa, 0x42, 0x87, 0xff, 0x7b, 0xa8, 0xdf, 0xba, 0x6b, 0x13, 0x17, 0x9c, 0x98,
	0xe0, 0x64, 0x1f, 0x9c, 0x8c, 0x21, 0x2f, 0x46, 0xf5, 0xf5, 0x57, 0xd7, 0x8b, 0xf7, 0xf2, 0xe0,
	0x11, 0xb7, 0x6c, 0x4c, 0x3e, 0x31, 0xbf, 0x1e, 0xfa, 0xd6, 0xdd, 0x21, 0xae, 0x17, 0x72, 0xe8,
	0x85, 0xbc, 0x1c, 0x7a, 0x19, 0x35, 0x8c, 0x7d, 0xf5, 0xdd, 0x45, 0x31, 0x76, 0x46, 0x43, 0x8d,
	0x9e, 0xd7, 0xdb, 0x08, 0x6d, 0xb6, 0x11, 0xfa, 0xd9, 0x46, 0x68, 0xb5, 0x8b, 0xbc, 0xcd, 0x2e,
	0xf2, 0x3e, 0x77, 0x91, 0xf7, 0x3a, 0xcc, 0x72, 0x3d, 0xab, 0x12, 0x92, 0x82, 0xa0, 0xee, 0x50,
	0xb7, 0xe6, 0xe9, 0x8e, 0xe3, 0xaa, 0xa3, 0x0b, 0x7a, 0x74, 0x5d, 0xbd, 0x2c, 0xb9, 0x4a, 0x7c,
	0xbb, 0xfc, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xde, 0x4b, 0xf3, 0x2a, 0xfa, 0x01, 0x00, 0x00,
}

func (m *Member) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Member) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Member) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreateTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CreateTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintMember(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMember(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.RemainCnt != 0 {
		i = encodeVarintMember(dAtA, i, uint64(m.RemainCnt))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalCnt != 0 {
		i = encodeVarintMember(dAtA, i, uint64(m.TotalCnt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MemberAddress) > 0 {
		i -= len(m.MemberAddress)
		copy(dAtA[i:], m.MemberAddress)
		i = encodeVarintMember(dAtA, i, uint64(len(m.MemberAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMember(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMember(dAtA []byte, offset int, v uint64) int {
	offset -= sovMember(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Member) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	l = len(m.MemberAddress)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	if m.TotalCnt != 0 {
		n += 1 + sovMember(uint64(m.TotalCnt))
	}
	if m.RemainCnt != 0 {
		n += 1 + sovMember(uint64(m.RemainCnt))
	}
	l = m.Amount.Size()
	n += 1 + l + sovMember(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreateTime)
	n += 1 + l + sovMember(uint64(l))
	return n
}

func sovMember(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMember(x uint64) (n int) {
	return sovMember(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Member) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Member: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Member: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCnt", wireType)
			}
			m.TotalCnt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCnt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainCnt", wireType)
			}
			m.RemainCnt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainCnt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreateTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMember(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMember
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMember
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMember
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMember
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMember        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMember          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMember = fmt.Errorf("proto: unexpected end of group")
)
